version: "3.2"

services:
    NIProducer:
        image: duartej/eutelescope:latest
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
        environment:
            - DISPLAY=unix${DISPLAY}
        depends_on:
            - "runControl"
            - "logger"
            - "dataCollector"
        networks:
            default:
                ipv4_address: 172.20.128.6
        entrypoint: 
            - initialize_service.sh
            - NIProducer

    TLU:
        image: duartej/eutelescope:latest
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /dev/bus/usb:/dev/bus/usb
        privileged: true
        environment:
            - DISPLAY=unix${DISPLAY}
        depends_on:
            - "runControl"
            - "logger"
            - "dataCollector"
        networks:
            default:
                ipv4_address: 172.20.128.7
        entrypoint: 
            - initialize_service.sh
            - TLU
