version: "3.2"

services:
    devcode:
        image: duartej/eutelescope:latest
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - type: bind
              source: @CODEDIR_EUDAQ
              target: /eudaq/eudaq
        environment:
            - DISPLAY=unix${DISPLAY}
        networks:
            default:
                ipv4_address: 172.20.128.20
    
    devcode-p:
        image: duartej/eutelescope:latest
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - type: bind
              source: @CODEDIR_EUDAQ
              target: /eudaq/eudaq
            - /dev/bus/usb:/dev/bus/usb
        privileged: true
        environment:
            - DISPLAY=unix${DISPLAY}
        networks:
            default:
                ipv4_address: 172.20.128.20
    
    runControl:
        volumes:
            - type: bind
              source: @CODEDIR_EUDAQ
              target: /eudaq/eudaq
    
    logger:
        volumes:
            - type: bind
              source: @CODEDIR_EUDAQ
              target: /eudaq/eudaq

    dataCollector:
        volumes:
            - type: bind
              source: @CODEDIR_EUDAQ
              target: /eudaq/eudaq
    onlineMon:
        volumes:
            - type: bind
              source: @CODEDIR_EUDAQ
              target: /eudaq/eudaq
    
    TLU:
        image: duartej/eutelescope:latest
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /dev/bus/usb:/dev/bus/usb
            - type: bind
              source: @CODEDIR_EUDAQ
              target: /eudaq/eudaq
        privileged: true
        environment:
            - DISPLAY=unix${DISPLAY}
        depends_on:
            - "runControl"
            - "logger"
            - "dataCollector"
            - "onlineMon"
        networks:
            default:
                ipv4_address: 172.20.128.7
        entrypoint: 
            - initialize_service.sh
            - TLU
    
    TestProducer:
        image: duartej/eutelescope:latest
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - type: bind
              source: @CODEDIR_EUDAQ
              target: /eudaq/eudaq
        environment:
            - DISPLAY=unix${DISPLAY}
        depends_on:
            - "runControl"
            - "logger"
        networks:
            default:
                ipv4_address: 172.20.128.6
        entrypoint: 
            - initialize_service.sh
            - TestProducer

